import os
from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits import create_sql_agent
from langchain_google_genai import ChatGoogleGenerativeAI

# 1. Set your Gemini API Key
os.environ["GOOGLE_API_KEY"] = st.secrets["GOOGLE_API_KEY"]
# 2. Connect the "Tool" (The Database)
# Guardrail: We explicitly tell the agent which tables exist and show it 3 sample rows
# so it doesn't have to guess column names or data types.
db = SQLDatabase.from_uri(
    "sqlite:///enterprise_data.db", 
    include_tables=['employees', 'customers', 'products', 'sales'],
    sample_rows_in_table_info=3 
)

# 3. Initialize the "Brain" (The LLM)
# Using Gemini 2.5 Flash for high speed and generous free-tier limits
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0)

# 4. Give the Agent a Strict Persona (Guardrails)
custom_prefix = """You are an expert Data Analyst AI. 
1. NEVER guess table names. ONLY use the tables explicitly provided in the database schema.
2. If you execute a SQL query and get an error, read the error message, correct your SQL, and try again automatically.
3. Always return the final answer in clear, plain English."""

# 5. Create the Agent Executor
agent_executor = create_sql_agent(
    llm, 
    db=db, 
    agent_type="tool-calling", 
    verbose=True,
    prefix=custom_prefix
)

# 6. Test the Reasoning Loop
if __name__ == "__main__":
    print("Agent initialized. Processing query...\n")
    
    # A complex Level 3 question to test JOINs and mathematical logic
    question = "Calculate the total profit generated by Alice Smith. Note that profit is calculated as (Price - CostToDeliver) multiplied by Quantity."
    
    # Run the agent
    response = agent_executor.invoke({"input": question})
    
    print("\n" + "="*40)
    print("FINAL ANSWER:")
    print("="*40)
    
    # Safely extract the output whether LangChain returns a dict or a string
    if isinstance(response, dict) and 'output' in response:
        print(response['output'])
    else:
        print(response)
